In [ ]:
#Week 1

In [ ]:
import numpy as np

In [5]:
number_array = np.array([10,20,30])
print(number_array)

[10 20 30]


In [6]:
#To import a specific function from a package
from math import radians

In [22]:
#Need to convert a List to an Array using Numpy to perform calculations
height = (1.75,1.85,1.86,1.65,1.88,1.92)
np_height = np.array(height)

weight = (60,70,80,90,91,82)
np_weight = np.array(weight)

#Calculation
bmi = np_weight/np_height**2

#Print
print(bmi)

#print bmi of person 2
print(bmi[1])
print(bmi > 30)
print(bmi[bmi > 30])
print(bmi[0:2])
print(bmi[:4])
print(bmi[4:])



[19.59183673 20.45288532 23.12406059 33.05785124 25.74694432 22.24392361]
20.45288531775018
[False False False  True False False]
[33.05785124]
[19.59183673 20.45288532]
[19.59183673 20.45288532 23.12406059 33.05785124]
[25.74694432 22.24392361]


In [ ]:
# 2D ARRAYS LECTURE

np_2D = np.array([[1.75,1.85,1.86,1.65,1.88,1.92],[60,70,80,90,91,82]])

print(np_2D)

np_2D.shape # 2 rows and 6 columns. This is an attribute it does not require brackets

#To select the row and column use the following syntax
print(np_2D[1][2]) # from the second row select the third column
print(np_2D[1,2]) # alternative method

In [34]:
#Select Multi values

print(np_2D[:,1:3]) # both rows columns 1 and 2

print(np_2D[1,:]) # row 2, all values

[[ 1.85  1.86]
 [70.   80.  ]]
[60. 70. 80. 90. 91. 82.]


In [57]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

# Print the third value
print(np_baseball[1:2,1:2])
print(np_baseball[1,1])
print(np_baseball[2, :])
print(np_baseball[:,1:])

<class 'numpy.ndarray'>
(4, 2)
[[102.7]]
102.7
[210.   98.5]
[[ 78.4]
 [102.7]
 [ 98.5]
 [ 75.2]]


In [89]:
# To complete statistical operations on an Array first need to do a subsetting operation to select the column

age = [25,26,27,29,32,45,23,25,26,35,44,37,20]
sex = ["m","f","f","f","m","m","f","f","m","m","m","f","f"]
date_set = np.array([age]+[sex])
#date_set = np.column_stack[age,sex]
print(date_set)

[['25' '26' '27' '29' '32' '45' '23' '25' '26' '35' '44' '37' '20']
 ['m' 'f' 'f' 'f' 'm' 'm' 'f' 'f' 'm' 'm' 'm' 'f' 'f']]


In [90]:
print(date_set.shape)

(2, 13)


In [ ]:
s_age = date_set[0,:]
print(s_age)
#av_age = np.mean(date_set[0,:])
#print(av_age)

In [72]:
print(type(date_set))

<class 'numpy.ndarray'>


In [130]:
#SIMULATED DATA SET

height = np.random.normal(1.75,0.20,3) #mean, stddev, number
print(height)

weight = np.random.normal(70,0.3,3)
print(weight)

#np_people = np.array([height]+[weight])
np_people = np.column_stack((height,weight)) #DOUBLE BRACKETS VERY IMPORTANT - THIS FUNCTION ALSO CHANGES THE SHAPE
print(np_people)
print(np_people.shape)

[1.45415865 1.85101519 1.79148255]
[70.14600471 70.22695783 69.65735049]
[[ 1.45415865 70.14600471]
 [ 1.85101519 70.22695783]
 [ 1.79148255 69.65735049]]
(3, 2)


In [131]:
print(np_people[:,0])

[1.45415865 1.85101519 1.79148255]


In [132]:
avg=np.mean(np_people[:,0])
print(avg)

1.698885463797599


In [135]:
#corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
JPR = np.corrcoef(np_people[:,0],np_people[:,1])
print(JPR)

[[ 1.         -0.24966671]
 [-0.24966671  1.        ]]
